//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1022
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsdl2Wsdl
{
	using System;
	using System.Web;
	using System.Web.UI;

	
	public partial class Default : System.Web.UI.Page
	{
			
	}
}

