//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4206
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
[System.Xml.Serialization.XmlRootAttribute("documentation", Namespace="http://www.w3.org/ns/wsdl", IsNullable=false)]
public partial class DocumentationType {

	private System.Xml.XmlNode[] anyField;

	private System.Xml.XmlAttribute[] anyAttrField;

	/// <remarks/>
	[System.Xml.Serialization.XmlTextAttribute()]
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	public System.Xml.XmlNode[] Any {
		get {
			return this.anyField;
		}
		set {
			this.anyField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyAttributeAttribute()]
	public System.Xml.XmlAttribute[] AnyAttr {
		get {
			return this.anyAttrField;
		}
		set {
			this.anyAttrField = value;
		}
	}
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ExtensibleDocumentedType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EndpointType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BindingFaultType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BindingOperationFaultType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BindingOperationMessageType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BindingOperationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BindingType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfaceFaultType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageRefFaultType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageRefType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfaceOperationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfaceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TypesType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(IncludeType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DescriptionType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
public partial class DocumentedType {

	private DocumentationType[] documentationField;

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("documentation")]
	public DocumentationType[] documentation {
		get {
			return this.documentationField;
		}
		set {
			this.documentationField = value;
		}
	}
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(EndpointType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BindingFaultType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BindingOperationFaultType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BindingOperationMessageType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BindingOperationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(BindingType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfaceFaultType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageRefFaultType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageRefType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfaceOperationType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(InterfaceType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(TypesType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(IncludeType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(ImportType))]
[System.Xml.Serialization.XmlIncludeAttribute(typeof(DescriptionType))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
public abstract partial class ExtensibleDocumentedType : DocumentedType {

	private System.Xml.XmlAttribute[] anyAttrField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyAttributeAttribute()]
	public System.Xml.XmlAttribute[] AnyAttr {
		get {
			return this.anyAttrField;
		}
		set {
			this.anyAttrField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
public partial class BindingFaultType : ExtensibleDocumentedType {

	private System.Xml.XmlElement[] itemsField;

	private System.Xml.XmlQualifiedName refField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	public System.Xml.XmlElement[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.Xml.XmlQualifiedName @ref {
		get {
			return this.refField;
		}
		set {
			this.refField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
public partial class BindingOperationFaultType : ExtensibleDocumentedType {

	private System.Xml.XmlElement[] itemsField;

	private System.Xml.XmlQualifiedName refField;

	private string messageLabelField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	public System.Xml.XmlElement[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.Xml.XmlQualifiedName @ref {
		get {
			return this.refField;
		}
		set {
			this.refField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
	public string messageLabel {
		get {
			return this.messageLabelField;
		}
		set {
			this.messageLabelField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
public partial class BindingOperationMessageType : ExtensibleDocumentedType {

	private System.Xml.XmlElement[] itemsField;

	private string messageLabelField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	public System.Xml.XmlElement[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
	public string messageLabel {
		get {
			return this.messageLabelField;
		}
		set {
			this.messageLabelField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
public partial class BindingOperationType : ExtensibleDocumentedType {

	private object[] itemsField;

	private ItemsChoiceType1[] itemsElementNameField;

	private System.Xml.XmlQualifiedName refField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	[System.Xml.Serialization.XmlElementAttribute("infault", typeof(BindingOperationFaultType))]
	[System.Xml.Serialization.XmlElementAttribute("input", typeof(BindingOperationMessageType))]
	[System.Xml.Serialization.XmlElementAttribute("outfault", typeof(BindingOperationFaultType))]
	[System.Xml.Serialization.XmlElementAttribute("output", typeof(BindingOperationMessageType))]
	[System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
	public object[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public ItemsChoiceType1[] ItemsElementName {
		get {
			return this.itemsElementNameField;
		}
		set {
			this.itemsElementNameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.Xml.XmlQualifiedName @ref {
		get {
			return this.refField;
		}
		set {
			this.refField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl", IncludeInSchema=false)]
public enum ItemsChoiceType1 {

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("##any:")]
	Item,

	/// <remarks/>
	infault,

	/// <remarks/>
	input,

	/// <remarks/>
	outfault,

	/// <remarks/>
	output,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
public partial class InterfaceFaultType : ExtensibleDocumentedType {

	private System.Xml.XmlElement[] itemsField;

	private string nameField;

	private string elementField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	public System.Xml.XmlElement[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
	public string name {
		get {
			return this.nameField;
		}
		set {
			this.nameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public string element {
		get {
			return this.elementField;
		}
		set {
			this.elementField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
public partial class MessageRefFaultType : ExtensibleDocumentedType {

	private System.Xml.XmlElement[] itemsField;

	private System.Xml.XmlQualifiedName refField;

	private string messageLabelField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	public System.Xml.XmlElement[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.Xml.XmlQualifiedName @ref {
		get {
			return this.refField;
		}
		set {
			this.refField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
	public string messageLabel {
		get {
			return this.messageLabelField;
		}
		set {
			this.messageLabelField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
public partial class MessageRefType : ExtensibleDocumentedType {

	private System.Xml.XmlElement[] itemsField;

	private string messageLabelField;

	private System.Xml.XmlQualifiedName elementField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	public System.Xml.XmlElement[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
	public string messageLabel {
		get {
			return this.messageLabelField;
		}
		set {
			this.messageLabelField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.Xml.XmlQualifiedName element
	{
		get {
			return this.elementField;
		}
		set {
			this.elementField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
public partial class InterfaceOperationType : ExtensibleDocumentedType {

	private object[] itemsField;

	private ItemsChoiceType[] itemsElementNameField;

	private string nameField;

	private string patternField;

	private bool safeField;

	private bool safeFieldSpecified;

	private string styleField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	[System.Xml.Serialization.XmlElementAttribute("infault", typeof(MessageRefFaultType))]
	[System.Xml.Serialization.XmlElementAttribute("input", typeof(MessageRefType))]
	[System.Xml.Serialization.XmlElementAttribute("outfault", typeof(MessageRefFaultType))]
	[System.Xml.Serialization.XmlElementAttribute("output", typeof(MessageRefType))]
	[System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
	public object[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public ItemsChoiceType[] ItemsElementName {
		get {
			return this.itemsElementNameField;
		}
		set {
			this.itemsElementNameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
	public string name {
		get {
			return this.nameField;
		}
		set {
			this.nameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
	public string pattern {
		get {
			return this.patternField;
		}
		set {
			this.patternField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public bool safe {
		get {
			return this.safeField;
		}
		set {
			this.safeField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlIgnoreAttribute()]
	public bool safeSpecified {
		get {
			return this.safeFieldSpecified;
		}
		set {
			this.safeFieldSpecified = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
	public string style {
		get {
			return this.styleField;
		}
		set {
			this.styleField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl", IncludeInSchema=false)]
public enum ItemsChoiceType {

	/// <remarks/>
	[System.Xml.Serialization.XmlEnumAttribute("##any:")]
	Item,

	/// <remarks/>
	infault,

	/// <remarks/>
	input,

	/// <remarks/>
	outfault,

	/// <remarks/>
	output,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
[System.Xml.Serialization.XmlRootAttribute("description", Namespace="http://www.w3.org/ns/wsdl", IsNullable=false)]
public partial class DescriptionType : ExtensibleDocumentedType {

	private object[] itemsField;

	private string targetNamespaceField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	[System.Xml.Serialization.XmlElementAttribute("binding", typeof(BindingType))]
	[System.Xml.Serialization.XmlElementAttribute("import", typeof(ImportType))]
	[System.Xml.Serialization.XmlElementAttribute("include", typeof(IncludeType))]
	[System.Xml.Serialization.XmlElementAttribute("interface", typeof(InterfaceType))]
	[System.Xml.Serialization.XmlElementAttribute("service", typeof(ServiceType))]
	[System.Xml.Serialization.XmlElementAttribute("types", typeof(TypesType))]
	public object[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
	public string targetNamespace {
		get {
			return this.targetNamespaceField;
		}
		set {
			this.targetNamespaceField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
[System.Xml.Serialization.XmlRootAttribute("binding", Namespace="http://www.w3.org/ns/wsdl", IsNullable=false)]
public partial class BindingType : ExtensibleDocumentedType {

	private object[] itemsField;

	private string nameField;

	private string typeField;

	private System.Xml.XmlQualifiedName interfaceField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	[System.Xml.Serialization.XmlElementAttribute("fault", typeof(BindingFaultType))]
	[System.Xml.Serialization.XmlElementAttribute("operation", typeof(BindingOperationType))]
	public object[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
	public string name {
		get {
			return this.nameField;
		}
		set {
			this.nameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
	public string type {
		get {
			return this.typeField;
		}
		set {
			this.typeField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.Xml.XmlQualifiedName @interface {
		get {
			return this.interfaceField;
		}
		set {
			this.interfaceField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
[System.Xml.Serialization.XmlRootAttribute("import", Namespace="http://www.w3.org/ns/wsdl", IsNullable=false)]
public partial class ImportType : ExtensibleDocumentedType {

	private System.Xml.XmlElement[] anyField;

	private string namespaceField;

	private string locationField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	public System.Xml.XmlElement[] Any {
		get {
			return this.anyField;
		}
		set {
			this.anyField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
	public string @namespace {
		get {
			return this.namespaceField;
		}
		set {
			this.namespaceField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
	public string location {
		get {
			return this.locationField;
		}
		set {
			this.locationField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
[System.Xml.Serialization.XmlRootAttribute("include", Namespace="http://www.w3.org/ns/wsdl", IsNullable=false)]
public partial class IncludeType : ExtensibleDocumentedType {

	private System.Xml.XmlElement[] anyField;

	private string locationField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	public System.Xml.XmlElement[] Any {
		get {
			return this.anyField;
		}
		set {
			this.anyField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
	public string location {
		get {
			return this.locationField;
		}
		set {
			this.locationField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
[System.Xml.Serialization.XmlRootAttribute("interface", Namespace="http://www.w3.org/ns/wsdl", IsNullable=false)]
public partial class InterfaceType : ExtensibleDocumentedType {

	private object[] itemsField;

	private string nameField;

	private System.Xml.XmlQualifiedName[] extendsField;

	private string[] styleDefaultField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	[System.Xml.Serialization.XmlElementAttribute("fault", typeof(InterfaceFaultType))]
	[System.Xml.Serialization.XmlElementAttribute("operation", typeof(InterfaceOperationType))]
	public object[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
	public string name {
		get {
			return this.nameField;
		}
		set {
			this.nameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.Xml.XmlQualifiedName[] extends {
		get {
			return this.extendsField;
		}
		set {
			this.extendsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
	public string[] styleDefault {
		get {
			return this.styleDefaultField;
		}
		set {
			this.styleDefaultField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
[System.Xml.Serialization.XmlRootAttribute("service", Namespace="http://www.w3.org/ns/wsdl", IsNullable=false)]
public partial class ServiceType : ExtensibleDocumentedType {

	private object[] itemsField;

	private string nameField;

	private System.Xml.XmlQualifiedName interfaceField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	[System.Xml.Serialization.XmlElementAttribute("endpoint", typeof(EndpointType))]
	public object[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
	public string name {
		get {
			return this.nameField;
		}
		set {
			this.nameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.Xml.XmlQualifiedName @interface {
		get {
			return this.interfaceField;
		}
		set {
			this.interfaceField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
[System.Xml.Serialization.XmlRootAttribute("endpoint", Namespace="http://www.w3.org/ns/wsdl", IsNullable=false)]
public partial class EndpointType : ExtensibleDocumentedType {

	private System.Xml.XmlElement[] itemsField;

	private string nameField;

	private System.Xml.XmlQualifiedName bindingField;

	private string addressField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	public System.Xml.XmlElement[] Items {
		get {
			return this.itemsField;
		}
		set {
			this.itemsField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="NCName")]
	public string name {
		get {
			return this.nameField;
		}
		set {
			this.nameField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute()]
	public System.Xml.XmlQualifiedName binding {
		get {
			return this.bindingField;
		}
		set {
			this.bindingField = value;
		}
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
	public string address {
		get {
			return this.addressField;
		}
		set {
			this.addressField = value;
		}
	}
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/ns/wsdl")]
[System.Xml.Serialization.XmlRootAttribute("types", Namespace="http://www.w3.org/ns/wsdl", IsNullable=false)]
public partial class TypesType : ExtensibleDocumentedType {

	private System.Xml.XmlElement[] anyField;

	/// <remarks/>
	[System.Xml.Serialization.XmlAnyElementAttribute()]
	public System.Xml.XmlElement[] Any {
		get {
			return this.anyField;
		}
		set {
			this.anyField = value;
		}
	}
}
